GET http://localhost:8081/films
Content-Type: application/json

###

POST http://localhost:8081/films/search
Content-Type: application/json

{
  "title": "Amadeus"
}

###

POST http://localhost:8081/films/genres
Content-Type: application/json

{
  "genre": "Action"
}