version: '3.8'
services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/code
    depends_on:
          - prometheus
          - pgdev
  pgdev:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YOUR_PASSWORD
    volumes:
      - "c:/repo/pgdev.db:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: YOUR_PASSWORD
    ports:
      - "5050:80"
  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    restart: always
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    env_file:
      - ./env/grafana.env


