spring:
  datasource:
    url: <YOUR_JDBC_URL>
    username: <YOUR_USERNAME>
    password: <YOUR_PASSWORD>
  jpa:
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false    

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    ROOT: INFO
    com.mallim: DEBUG
