spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvdrental
    username: postgres
    password: zaq12wsx
  jpa:
    show-sql: true

server:
  port: 8081

logging:
  level:
    ROOT: INFO
    com.mallim: DEBUG