spring:
  datasource:
    url: <YOUR_JDBC_URL>
    username: <YOUR_USERNAME>
    password: <YOUR_PASSWORD>
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    ROOT: INFO
    com.mallim: DEBUG