GET http://{{host}}/films
Content-Type: application/json

###

POST http://{{host}}/films/search
Content-Type: application/json

{
  "title": "Amadeus"
}

###

POST http://{{host}}/films/genres
Content-Type: application/json

{
  "genre": "Action"
}